### ISSUE TITLE
Could you please tell me how to get the embed_tfidf_weights.pkl

### ISSUE THREAD

**Issue by Victory0622** [aioz-ai/MICCAI21_MMQ#16]

**Comment by YAO-EE** [comment]
> _No description provided._

Hi，
I also encountered this problem. Has it been solved for you?

**Comment by xuanbinh-nguyen96** [comment]
In [dataset_VQA.py](https://github.com/aioz-ai/MICCAI21_MMQ/blob/main/dataset_VQA.py), we attach source code (in comment format) from line 317 to line 323 for creating the embed_tfidf_weights.pkl
